"""initial_schema

Revision ID: 0d768b73cbb0
Revises:
Create Date: 2026-09-10 15:41:25.049014
"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

from apps.api.app.db.base import UTCDateTime

revision: str = "0d768b73cbb0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('ADMIN','EDITOR')", name=op.f("ck_users_role")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_brands_revision_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_brands_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("operation", sa.String(length=200), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "response",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("expires_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status_code >= 100 AND status_code <= 599",
            name=op.f("ck_idempotency_keys_status_code"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_idempotency_keys_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint(
            "user_id", "operation", "key", name="uq_idempotency_keys_user_operation_key"
        ),
    )
    op.create_index(
        op.f("ix_idempotency_keys_expires_at"), "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_projects_revision_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_projects_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "workflow_registry",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column(
            "workflow",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "slots",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "required_slots",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "profile",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("workflow_hash", sa.String(length=64), nullable=False),
        sa.Column("slot_map_hash", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("approved_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "mode IN ('t2v','i2v','i2v_first_last','r2v')", name=op.f("ck_workflow_registry_mode")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_workflow_registry_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_registry")),
        sa.UniqueConstraint("code", "version", name="uq_workflow_registry_code_version"),
    )
    op.create_table(
        "products",
        sa.Column("brand_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_products_revision_positive")),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_products_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_products_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_brand_id"), "products", ["brand_id"], unique=False)
    op.create_table(
        "assets",
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("product_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("deleted_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('IMAGE','VIDEO','AUDIO')", name=op.f("ck_assets_kind")),
        sa.CheckConstraint(
            "status IN ('PENDING','PENDING_UPLOAD','VALIDATING','READY','FAILED','DELETED')",
            name=op.f("ck_assets_status"),
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds > 0",
            name=op.f("ck_assets_duration_positive"),
        ),
        sa.CheckConstraint("height IS NULL OR height > 0", name=op.f("ck_assets_height_positive")),
        sa.CheckConstraint(
            "project_id IS NULL OR product_id IS NULL", name=op.f("ck_assets_single_business_scope")
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_assets_size_nonnegative")),
        sa.CheckConstraint("width IS NULL OR width > 0", name=op.f("ck_assets_width_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_assets_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_assets_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_assets_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("object_key", name=op.f("uq_assets_object_key")),
    )
    op.create_index(op.f("ix_assets_product_id"), "assets", ["product_id"], unique=False)
    op.create_index(op.f("ix_assets_project_id"), "assets", ["project_id"], unique=False)
    op.create_index("ix_assets_status_created_at", "assets", ["status", "created_at"], unique=False)
    op.create_table(
        "videos",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=True),
        sa.Column("brand_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("target_duration", sa.Float(), nullable=False),
        sa.Column("aspect_ratio", sa.String(length=16), nullable=False),
        sa.Column("brief", sa.Text(), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("current_final_video_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('QUICK_CLIP','LONG_VIDEO')", name=op.f("ck_videos_kind")),
        sa.CheckConstraint(
            "status IN ('DRAFT','PLANNING','STORYBOARD_READY','GENERATING','SCENES_READY','ASSEMBLING','READY','DIRTY','FAILED')",
            name=op.f("ck_videos_status"),
        ),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_videos_revision_positive")),
        sa.CheckConstraint("target_duration > 0", name=op.f("ck_videos_duration_positive")),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_videos_brand_id_brands"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_videos_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["current_final_video_id", "id"],
            ["final_videos.id", "final_videos.video_id"],
            name="fk_videos_current_final_same_video",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_videos_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_videos_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
    )
    op.create_index(op.f("ix_videos_product_id"), "videos", ["product_id"], unique=False)
    op.create_index(
        "ix_videos_project_created", "videos", ["project_id", "created_at", "id"], unique=False
    )
    op.create_table(
        "final_videos",
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "assembly_config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("output_asset_id", sa.String(length=36), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=64), nullable=False),
        sa.Column("progress_current", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("started_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("progress_updated_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('QUEUED','ASSEMBLING','READY','FAILED','CANCEL_REQUESTED','CANCELLED')",
            name=op.f("ck_final_videos_status"),
        ),
        sa.CheckConstraint(
            "progress_current >= 0 AND progress_total >= 0 AND progress_current <= progress_total",
            name=op.f("ck_final_videos_progress"),
        ),
        sa.CheckConstraint(
            "revision >= 1 AND version_no >= 1 AND attempt_count >= 0",
            name=op.f("ck_final_videos_counters"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_final_videos_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["output_asset_id"],
            ["assets.id"],
            name=op.f("fk_final_videos_output_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_final_videos_video_id_videos"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_final_videos")),
        sa.UniqueConstraint("id", "video_id", name="uq_final_videos_id_video"),
        sa.UniqueConstraint("video_id", "version_no", name="uq_final_videos_video_version"),
    )
    op.create_index(
        "ix_final_videos_dispatch",
        "final_videos",
        ["status", "lease_expires_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_final_videos_request_id"), "final_videos", ["request_id"], unique=False
    )
    op.create_table(
        "scenes",
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("scene_order", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("negative_prompt", sa.Text(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column(
            "spec",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("selected_generation_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("duration_seconds > 0", name=op.f("ck_scenes_duration_positive")),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_scenes_revision_positive")),
        sa.CheckConstraint("scene_order >= 0", name=op.f("ck_scenes_order_nonnegative")),
        sa.ForeignKeyConstraint(
            ["selected_generation_id", "id"],
            ["scene_generations.id", "scene_generations.scene_id"],
            name="fk_scenes_selected_same_scene",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_scenes_video_id_videos"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenes")),
        sa.UniqueConstraint("id", "video_id", name="uq_scenes_id_video"),
        sa.UniqueConstraint("video_id", "scene_order", name="uq_scenes_video_order"),
    )
    op.create_index(
        "ix_scenes_video_order", "scenes", ["video_id", "scene_order", "id"], unique=False
    )
    op.create_table(
        "scene_generations",
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("generation_no", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("parent_generation_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("phase", sa.String(length=64), nullable=False),
        sa.Column("progress_current", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "input_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("comfy_prompt_id", sa.String(length=128), nullable=True),
        sa.Column("output_asset_id", sa.String(length=36), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("queued_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("started_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("progress_updated_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "mode IN ('t2v','i2v','i2v_first_last','r2v')", name=op.f("ck_scene_generations_mode")
        ),
        sa.CheckConstraint(
            "operation IN ('ORIGINAL','REGENERATE','VARIATION')",
            name=op.f("ck_scene_generations_operation"),
        ),
        sa.CheckConstraint(
            "status IN ('CREATED','DISPATCHING','QUEUED','RUNNING','COLLECTING','COMPLETED','FAILED','CANCEL_REQUESTED','CANCELLED')",
            name=op.f("ck_scene_generations_status"),
        ),
        sa.CheckConstraint(
            "parent_generation_id IS NULL OR parent_generation_id <> id",
            name=op.f("ck_scene_generations_not_own_parent"),
        ),
        sa.CheckConstraint(
            "progress_current >= 0 AND progress_total >= 0 AND progress_current <= progress_total",
            name=op.f("ck_scene_generations_progress"),
        ),
        sa.CheckConstraint(
            "revision >= 1 AND generation_no >= 1 AND attempt_count >= 0",
            name=op.f("ck_scene_generations_counters"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_scene_generations_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["output_asset_id"],
            ["assets.id"],
            name=op.f("fk_scene_generations_output_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_generation_id", "scene_id"],
            ["scene_generations.id", "scene_generations.scene_id"],
            name="fk_generations_parent_same_scene",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id", "video_id"],
            ["scenes.id", "scenes.video_id"],
            name=op.f("fk_scene_generations_scene_id_scenes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_scene_generations_video_id_videos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_registry.id"],
            name=op.f("fk_scene_generations_workflow_id_workflow_registry"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_generations")),
        sa.UniqueConstraint("comfy_prompt_id", name=op.f("uq_scene_generations_comfy_prompt_id")),
        sa.UniqueConstraint("id", "scene_id", name="uq_scene_generations_id_scene"),
        sa.UniqueConstraint("scene_id", "generation_no", name="uq_scene_generations_scene_number"),
    )
    op.create_index(
        "ix_scene_generations_dispatch",
        "scene_generations",
        ["status", "lease_expires_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scene_generations_request_id"), "scene_generations", ["request_id"], unique=False
    )
    op.create_index(
        "ix_scene_generations_video_created",
        "scene_generations",
        ["video_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "final_video_scenes",
        sa.Column("final_video_id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=False),
        sa.Column("scene_order", sa.Integer(), nullable=False),
        sa.Column("generation_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("asset_checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "transition_config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scene_order >= 0", name=op.f("ck_final_video_scenes_order_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_final_video_scenes_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["final_video_id"],
            ["final_videos.id"],
            name=op.f("fk_final_video_scenes_final_video_id_final_videos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["generation_id", "scene_id"],
            ["scene_generations.id", "scene_generations.scene_id"],
            name="fk_final_scene_generation_same_scene",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
            name=op.f("fk_final_video_scenes_scene_id_scenes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_final_video_scenes")),
        sa.UniqueConstraint("final_video_id", "scene_id", name="uq_final_video_scenes_scene"),
        sa.UniqueConstraint("final_video_id", "scene_order", name="uq_final_video_scenes_order"),
    )
    op.create_table(
        "generation_assets",
        sa.Column("generation_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("order_index >= 0", name=op.f("ck_generation_assets_order_nonnegative")),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_generation_assets_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["scene_generations.id"],
            name=op.f("fk_generation_assets_generation_id_scene_generations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_assets")),
        sa.UniqueConstraint(
            "generation_id", "role", "order_index", name="uq_generation_assets_slot"
        ),
    )
    op.create_index(
        op.f("ix_generation_assets_asset_id"), "generation_assets", ["asset_id"], unique=False
    )
    op.create_table(
        "generation_attempts",
        sa.Column("generation_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("client_id", sa.String(length=128), nullable=False),
        sa.Column("comfy_prompt_id", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("finished_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('CREATED','DISPATCHING','QUEUED','RUNNING','COLLECTING','COMPLETED','FAILED','CANCELLED','UNKNOWN')",
            name=op.f("ck_generation_attempts_status"),
        ),
        sa.CheckConstraint("attempt_no >= 1", name=op.f("ck_generation_attempts_attempt_positive")),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["scene_generations.id"],
            name=op.f("fk_generation_attempts_generation_id_scene_generations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_attempts")),
        sa.UniqueConstraint("client_id", name=op.f("uq_generation_attempts_client_id")),
        sa.UniqueConstraint("comfy_prompt_id", name=op.f("uq_generation_attempts_comfy_prompt_id")),
        sa.UniqueConstraint("generation_id", "attempt_no", name="uq_generation_attempts_number"),
    )
    if op.get_bind().dialect.name == "postgresql":
        op.create_foreign_key(
            "fk_videos_current_final_same_video",
            "videos",
            "final_videos",
            ["current_final_video_id", "id"],
            ["id", "video_id"],
            ondelete="RESTRICT",
        )
        op.create_foreign_key(
            "fk_scenes_selected_same_scene",
            "scenes",
            "scene_generations",
            ["selected_generation_id", "id"],
            ["id", "scene_id"],
            ondelete="RESTRICT",
        )
        op.execute(
            """
            CREATE FUNCTION reject_final_manifest_mutation() RETURNS trigger AS $$
            BEGIN
                IF NEW.video_id IS DISTINCT FROM OLD.video_id
                   OR NEW.version_no IS DISTINCT FROM OLD.version_no
                   OR NEW.manifest IS DISTINCT FROM OLD.manifest
                   OR NEW.manifest_hash IS DISTINCT FROM OLD.manifest_hash
                   OR NEW.assembly_config IS DISTINCT FROM OLD.assembly_config THEN
                    RAISE EXCEPTION 'immutable final assembly manifest cannot be changed';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
            """
        )
        op.execute(
            """
            CREATE TRIGGER trg_final_manifest_immutable
            BEFORE UPDATE ON final_videos
            FOR EACH ROW EXECUTE FUNCTION reject_final_manifest_mutation()
            """
        )
        op.execute(
            """
            CREATE FUNCTION reject_final_scene_mutation() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'immutable final assembly scene cannot be changed or deleted';
            END;
            $$ LANGUAGE plpgsql
            """
        )
        op.execute(
            """
            CREATE TRIGGER trg_final_scene_immutable
            BEFORE UPDATE OR DELETE ON final_video_scenes
            FOR EACH ROW EXECUTE FUNCTION reject_final_scene_mutation()
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER trg_final_scene_immutable ON final_video_scenes")
        op.execute("DROP FUNCTION reject_final_scene_mutation()")
        op.execute("DROP TRIGGER trg_final_manifest_immutable ON final_videos")
        op.execute("DROP FUNCTION reject_final_manifest_mutation()")
        op.drop_constraint("fk_scenes_selected_same_scene", "scenes", type_="foreignkey")
        op.drop_constraint("fk_videos_current_final_same_video", "videos", type_="foreignkey")
    op.drop_table("generation_attempts")
    op.drop_index(op.f("ix_generation_assets_asset_id"), table_name="generation_assets")
    op.drop_table("generation_assets")
    op.drop_table("final_video_scenes")
    op.drop_index("ix_scene_generations_video_created", table_name="scene_generations")
    op.drop_index(op.f("ix_scene_generations_request_id"), table_name="scene_generations")
    op.drop_index("ix_scene_generations_dispatch", table_name="scene_generations")
    op.drop_table("scene_generations")
    op.drop_index("ix_scenes_video_order", table_name="scenes")
    op.drop_table("scenes")
    op.drop_index(op.f("ix_final_videos_request_id"), table_name="final_videos")
    op.drop_index("ix_final_videos_dispatch", table_name="final_videos")
    op.drop_table("final_videos")
    op.drop_index("ix_videos_project_created", table_name="videos")
    op.drop_index(op.f("ix_videos_product_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index("ix_assets_status_created_at", table_name="assets")
    op.drop_index(op.f("ix_assets_project_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_product_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_products_brand_id"), table_name="products")
    op.drop_table("products")
    op.drop_table("workflow_registry")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("projects")
    op.drop_index(op.f("ix_idempotency_keys_expires_at"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_table("brands")
    op.drop_table("users")
    # ### end Alembic commands ###
